config/routes.rb
GAilyApp::Application.routes.draw do
  
  get "/" => "home#index", as: "home"
  root to: "home#index"

  resources :courses do
    resources :enrollments, only: [:new, :create, :edit, :update, :destroy]
    resources :assignments, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :classrooms
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  post "courses/:id/delete" => "courses#destroy", as: "delete_course"
  post "users/:id/delete" => "users#destroy", as: "delete_user"
  post "classrooms/:id/delete" => "classrooms#destroy", as: "delete_classroom"
  post "courses/:course_id/enrollments/:id" => "enrollments#destroy", as: "delete_course_enrollment"
  post "courses/:course_id/assignments/:id" => "assignments#destroy", as: "delete_course_assignment"

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  attr_accessible :equipment, :name, :other_aspects

  validates :equipment, :name, :other_aspects, presence: true
  validates :name, uniqueness: true

  has_many :bookings
  has_many :courses, through: :bookings
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  load_and_authorize_resource

  def index
    @q = Classroom.search(params[:q])
    @classrooms = @q.result(distinct: true).order(:name)
  end

  def new
  end

  def create
    @classroom = Classroom.new(params[:classroom])
    if @classroom.save
      redirect_to @classroom, notice: "#{@classroom.name} has been added."
    else
      render 'new'
    end
  end

  def show
    @bookings = Booking.where(classroom_id: params[:id])
  end

  def edit
  end

  def update
    if @classroom.update_attributes(params[:classroom])
      redirect_to @classroom, notice: "#{@classroom.name} has been updated."
    else
      render 'edit'
    end
  end

  def destroy
    Classroom.destroy(params[:id])
    redirect_to classrooms_path, notice: "Classroom has been removed."
  end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/views/classrooms/_form.html.erb
<div class="frame small">
  <%= form_for @classroom do |f| %>
    <% if @classroom.errors.any? %>
      <div id="error_explanation">
        <h3><%= @classroom.errors.full_messages.join(", ").downcase.capitalize %>.</h3>
      </div>
    <% end %>
    
    <%= f.label :name %><br />
    <%= f.text_field :name, size: "38", placeholder: "Indicate if for (Day) or (Night) use..." %><br />
    <%= f.label :equipment %><br />
    <%= f.text_area :equipment, rows: "10" %><br /> 
    <%= f.label :other_aspects %><br />
    <%= f.text_area :other_aspects, rows: "10" %><br />
    <%= f.submit "Submit" %>
  <% end %>
</div>
<div class="frame button">
  <%= button_to "Cancel", classrooms_path, method: :get %>
</div>

app/views/classrooms/edit.html.erb
<div class="frame small">
  <h2>Edit</h2>
  <h3><%= @classroom.name %></h3>
</div>

<%= render 'form' %>

app/views/classrooms/index.html.erb
<div class="frame small">
  <h2>Classrooms</h2>
  <%= search_form_for @q do |f| %>
    <%= f.label "Search" %>
    <%= f.text_field :name_cont, placeholder: " enter classroom name" %>
    <%= f.submit %><br /><br />
  <% end %>
</div>
<% @classrooms.each do |classroom| %>
  <div class="frame small classroom">
    <h4>
      <%= link_to classroom.name, classroom %>
    </h4>
    <ul>
      <li>
        Equipment: <%= classroom.equipment %>
      </li>
      <li>
        Other aspects: <%= classroom.other_aspects %>
      </li>
      <li>
        <%= button_to "Edit", edit_classroom_path(classroom), method: :get %>
        <%= button_to "Delete", delete_classroom_path(classroom) %>
      </li>
    </ul>
  </div>
<% end %>
<br />
<div class="frame list-button">
  <%= button_to "New Classroom", new_classroom_path, method: :get %>
</div>

app/views/classrooms/new.html.erb
<div class="frame small">
  <h2>Add Classroom</h2>
</div>

<%= render 'form' %>

app/views/classrooms/show.html.erb
<div class="frame medium">
  <h2>
    <%= @classroom.name %>
  </h2>
  <ul>
    <li>
      Equipment: <%= @classroom.equipment %>
    </li>
    <li>
      Other aspects: <%= @classroom.other_aspects %>
    </li>
    <li>
      <br />
      <%= button_to "Edit", edit_classroom_path(@classroom), method: :get %>
      <%= button_to "Delete", delete_classroom_path(@classroom) %>
    </li>
  </ul>
</div>
<div class="frame medium">
  <h3>Bookings</h3>
  <% if @bookings.empty? %>
    <p>There are no bookings for this classroom.</p>
  <% else %>
    <% @bookings.each do |booking| %>
      <ul>
        <li> Course: <%= link_to booking.course.name, course_path(booking.course) %>
        </li>
        <li>
          Start Date: <%= booking.start_date %>
        </li>
        <li>
          End Date: <%= booking.end_date %>
        </li>
      </ul>
    <% end %>
  <% end %>
  <ul>
    <li>
      <%= button_to "Add a Course", new_course_path, method: :get %>
    </li>
  </ul>
</div>
<div class="frame list-button">
  <%= button_to "Classrooms", classrooms_path, method: :get %>
</div>