config/routes.rb
GAilyApp::Application.routes.draw do
  
  get "/" => "home#index", as: "home"
  root to: "home#index"

  resources :courses do
    resources :enrollments, only: [:new, :create, :edit, :update, :destroy]
    resources :assignments, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :classrooms
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  post "courses/:id/delete" => "courses#destroy", as: "delete_course"
  post "users/:id/delete" => "users#destroy", as: "delete_user"
  post "classrooms/:id/delete" => "classrooms#destroy", as: "delete_classroom"
  post "courses/:course_id/enrollments/:id" => "enrollments#destroy", as: "delete_course_enrollment"
  post "courses/:course_id/assignments/:id" => "assignments#destroy", as: "delete_course_assignment"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :first_name, :last_name, :role, :username, :password, :password_confirmation, :image

  mount_uploader :image, ImageUploader

  has_many :enrollments, foreign_key: "student_id"
  has_many :assignments, foreign_key: "instructor_id"
  has_many :courses, through: :enrollments
  has_many :courses, through: :assignments

  validates :first_name, :last_name, :role, :username, presence: true

  def role?(role_to_compare)
    self.role.to_s == role_to_compare.to_s
  end

  def full_name
    "#{first_name} #{last_name}"
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
load_and_authorize_resource

  def index
    @students = User.where(role: :student).order(:last_name)
    @instructors = User.where(role: :instructor).order(:last_name)
    @admins = User.where(role: :admin).order(:last_name)
  end

  def new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      redirect_to users_path, notice: "User has been successfully added."
    else
      render :new
    end
  end

  def edit
  end

  def show
  end

  def update
    if @user.update_attributes(params[:user])
      redirect_to(user_path(@user), notice: "#{@user.username} has been successfully updated.")
    else
      render action: 'edit'
    end
  end

  def destroy
    if session[:current_user_id] == params[:id].to_i
      User.destroy(params[:id])
      redirect_to(root_url, notice: "You have been removed.")
    else
      User.destroy(params[:id])
      redirect_to(users_path, notice: "User has been removed.")
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def true_if_admin
    true if current_user && current_user.role?(:admin) && current_user.id != @user.id
  end

  def true_unless_admin
    (current_user && current_user.role?(:admin)) ? false : true
  end

  def get_image(user)
    if user.image.blank?
      image_tag "default.jpg"
    else
      image_tag user.image.url(:main)
    end
  end

  def get_image_thumb(user)
    if user.image.blank?
      image_tag "default_thumb.jpeg"
    else
      image_tag user.image.url(:thumb)
    end
  end

end

app/views/users/_form.html.erb
<div class="frame small">
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h3><%= @user.errors.full_messages.join(", ").downcase.capitalize %>.</h3>
      </div>
    <% end %>

    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, readonly: true_unless_admin %><br />
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name, readonly: true_unless_admin %><br />
    <%= f.label :username %><br />
    <%= f.text_field :username, placeholder: "Enter your email address", readonly: true_if_admin && @user.id %><br />
    <%= f.label :password %><br />
    <%= f.password_field :password, readonly: true_if_admin && @user.id %><br />
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, readonly: true_if_admin && @user.id %><br />
    <% if current_user.id == @user.id %>
      <%= f.label "Profile Image" %>
      <%= f.file_field :image %><br />
    <% end %>
    <% if true_if_admin %>
      <%= f.label :role %><br />
      <%= f.select :role, [["Administrator", :admin],["Instructor", :instructor],["Student", :student]] %><br />
    <% end %>
    <br />
    <%= f.submit "Submit" %>
  <% end %>
</div>
<div class="frame button">
  <%= button_to "Cancel", users_path, method: :get %>
</div>

app/views/users/_user_information.html.erb
<% users.each do | user | %>
  <div class="information">
    <ul>
      <li><%= get_image_thumb(user) %></li>
      <li>Name: <%= link_to user.full_name, user_path(user) %></li>
      <li>Username: <%= user.username %></li>
      <br />
      <li>
        <% if can? :update, user %>
          <%= button_to "Edit", edit_user_path(user), method: :get %>
        <% end %>
        <% if can? :destroy, user %>
          <%= button_to "Delete", delete_user_path(user) %>
        <% end %>
      </li>    
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="frame small">
  <h2>Edit</h2>
  <h3><%= current_user.id == @user.id ? "Your" : "#{@user.full_name}'s" %> Credentials</h3>
</div>


<%= render 'form' %>

app/views/users/index.html.erb
<div class="frame small">
  <h2>Users</h2>
</div>
<div class="frame medium">
  <% if @admins.any? %>
    <h3>Administrators</h3>
    <%= render partial: 'user_information', locals: {users: @admins } %>
  <% end %>
</div>
<div class="frame medium">
  <% if @instructors.any? %>
    <h3>Instructors</h3>
    <%= render partial: 'user_information', locals: {users: @instructors } %>
  <% end %>
</div>
<div class="frame medium">
  <% if @students.any? %>
    <h3>Students</h3>
    <%= render partial: 'user_information', locals: {users: @students } %>
  <% end %>
</div>
<div class="frame list-button">
  <ul>
    <li>
      <%= button_to "Add User", new_user_path, method: :get %>
    </li>
  </ul>
</div>

app/views/users/new.html.erb
<div class="frame small">
  <h2>Add User</h2>
</div>


<%= render 'form' %>

app/views/users/show.html.erb
<div class="frame small">
  <h2><%= @user.full_name %></h2>
  <%= get_image(@user) %>
  <ul>
    <li>Name: <%= @user.full_name %></li>
    <li>Username: <%= @user.username %></li>
    <br />
    <li>
      <% if can? :update, @user %>
        <%= button_to "Edit", edit_user_path(@user), method: :get %>
      <% end %>
      <% if can? :destroy, @user %>
        <%= button_to "Delete", delete_user_path(@user) %>
      <% end %>
    </li>    
  </ul>
  <% if @user.assignments.any? %>
    <h4>
      <li>Assignments</li>
    </h4>
    <br />
    <% @user.assignments.each do |assignment| %>
      <ul>
        <li>
          Course: <%= link_to assignment.course.name, course_path(assignment.course) %>
        </li>
        <li>
          Start Date: <%= assignment.course.booking.start_date %>
        </li>
        <li>
          End Date: <%= assignment.course.booking.end_date %>
        </li>
      </ul>
    <% end %>
  <% end %>
  <% if @user.enrollments.any? %>
    <h4>
      <li>Enrollments</li>
    </h4>
    <% @user.enrollments.each do |enrollment| %>
      <ul>
        <li>
          Course: <%= link_to enrollment.course.name, course_path(enrollment.course) %>
        </li>
        <li>
          Start Date: <%= enrollment.course.booking.start_date %>
        </li>
        <li>
          End Date: <%= enrollment.course.booking.end_date %>
        </li>
      </ul>
    <% end %>
  <% end %>
  <ul>
    <li>
      <%= button_to "Users", users_path, method: :get %>
    </li>
  </ul>
</div>