config/routes.rb
GAilyApp::Application.routes.draw do
  
  get "/" => "home#index", as: "home"
  root to: "home#index"

  resources :courses do
    resources :enrollments, only: [:new, :create, :edit, :update, :destroy]
    resources :assignments, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :classrooms
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  post "courses/:id/delete" => "courses#destroy", as: "delete_course"
  post "users/:id/delete" => "users#destroy", as: "delete_user"
  post "classrooms/:id/delete" => "classrooms#destroy", as: "delete_classroom"
  post "courses/:course_id/enrollments/:id" => "enrollments#destroy", as: "delete_course_enrollment"
  post "courses/:course_id/assignments/:id" => "assignments#destroy", as: "delete_course_assignment"

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  load_and_authorize_resource

  def index
    @q = Course.search(params[:q])
    @courses = @q.result(distinct: true)
  end

  def new
    @course.build_booking    
  end

  def create

    @course = Course.new(params[:course])

    validate_dates

    if @invalid_date_error
      flash.now[:notice] = @invalid_date_error
      render action: "new"
    elsif overlapped_bookings?(@new_start_date, @new_end_date)
      overlap_error = "Course overlaps with #{@overlapped_bookings.length} other courses: "
      overlapped_courses = @overlapped_bookings.map { |booking|
        booking.course.name }
      overlap_error << overlapped_courses.to_sentence
      overlap_error << "."
      flash.now[:notice] = overlap_error
      render action: "new"
    elsif course_start_time_before_end_time?
      flash.now[:notice] = "Invalid start and end times."
      render action: "new"
    else
      if @course.save
        redirect_to @course, notice: "#{@course.name} has been added."
      else
        render action: "new"
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    validate_dates

    if @invalid_date_error
      flash.now[:notice] = @invalid_date_error
      render action: "edit"
    elsif overlapped_bookings?(@new_start_date, @new_end_date)
      overlap_error = "Course overlaps with: "
      overlapped_courses = @overlapped_bookings.map { |booking|
        booking.course.name }
      overlap_error << overlapped_courses.to_sentence
      overlap_error << "."
      flash.now[:notice] = overlap_error
      render action: "edit"
    elsif course_start_time_before_end_time?
      flash.now[:notice] = "Invalid start and end times."
      render action: "edit"
    else
      if @course.update_attributes(params[:course])
        redirect_to @course, notice: "#{@course.name} has been updated."
      else
        render action: "edit"
      end
    end
  end

  def destroy
    Course.destroy(params[:id])
    redirect_to courses_path, notice: "Course has been deleted."
  end

  def overlapped_bookings?(new_start_date, new_end_date)

    @course.id ||= 0

    @overlapped_bookings = Booking.where("classroom_id = #{params[:course][:booking_attributes][:classroom_id]} AND course_id != #{@course.id} AND (start_date between '#{new_start_date}' AND '#{new_end_date}' OR end_date between '#{new_start_date}' AND '#{new_end_date}')")

    if @overlapped_bookings && @overlapped_bookings.any?
      true
    else
      false
    end
  end

  def validate_dates
    booking = params[:course][:booking_attributes]
    
    start_year = booking["start_date(1i)"].to_i
    start_month = booking["start_date(2i)"].to_i
    start_day = booking["start_date(3i)"].to_i
    end_year = booking["end_date(1i)"].to_i
    end_month = booking["end_date(2i)"].to_i
    end_day = booking["end_date(3i)"].to_i
    
    if Date.valid_date?(start_year, start_month, start_day) && Date.valid_date?(end_year, end_month, end_day)
      @new_start_date = Date.new(start_year, start_month, start_day)
      @new_end_date = Date.new(end_year, end_month, end_day)
    else
      if !Date.valid_date?(start_year, start_month, start_day)
        invalid_date_error = "Start date is invalid"
      end
      if invalid_date_error && !Date.valid_date?(end_year, end_month, end_day)
        invalid_date_error << " and end date is invalid"
      elsif !Date.valid_date?(end_year, end_month, end_day)
        invalid_date_error = "End date is invalid"
      end
      invalid_date_error << "."
      @invalid_date_error = invalid_date_error
    end
  end

  def course_start_time_before_end_time?
    
    if params[:course][:end_time].to_i <= params[:course][:start_time].to_i
      true
    else
      false
    end
  end

  

end

app/helpers/courses_helper.rb
module CoursesHelper

  
end

app/views/courses/_assignments.html.erb
<ol>
  <% @course.assignments.each do |assignment| %>
    <li>
      <ul>
        <li>
          Instructor: <%= link_to "#{assignment.instructor.first_name} #{assignment.instructor.last_name}", user_path(assignment.instructor) %>
        </li>
        <li>
          Username: <%= assignment.instructor.username %>
        </li>
        <li>
          <% if can? :manage, Enrollment %>
            Contract fee: <%= number_to_currency(assignment.contract_fee, unit: "£") %>
          <% end %>
        </li>
        <li>
          Position: <%= assignment.position.capitalize %>
          <br /><br />
        </li>
        <li>
          <% if can? :manage, Assignment %>
            <%= button_to "Edit", edit_course_assignment_path(@course.id, assignment), method: :get %>
            <%= button_to "Delete", delete_course_assignment_path(@course.id, assignment) %>
          <% end %>
          <br /><br />
        </li>
      </ul>
    </li>
  <% end %>
</ol>

app/views/courses/_booking.html.erb
<li> Classroom: <%= link_to @course.booking.classroom.name, classroom_path(@course.booking.classroom) %>
</li>
<li>
  Start Date: <%= @course.booking.start_date %>
</li>
<li>
  End Date: <%= @course.booking.end_date %>
</li>

app/views/courses/_enrollments.html.erb
<ol>
  <% @course.enrollments.each do |enrollment| %>
    <li>
      <ul>
        <li>
          Student: <%= link_to "#{enrollment.student.first_name} #{enrollment.student.last_name}", user_path(enrollment.student) %>
        </li>
        <li>
          Username: <%= enrollment.student.username %>
        </li>
        <li>
          Paid deposit? <%= enrollment.paid_deposit ? "Yes" : "No" %>
        </li>
        <li>
          Completed the pre-work? <%= enrollment.pre_work %>
          <br /><br />
        </li>
        <li>
          <% if can? :manage, Enrollment %>
            <%= button_to "Edit", edit_course_enrollment_path(@course.id, enrollment), method: :get %>
            <%= button_to "Delete", delete_course_enrollment_path(@course.id, enrollment) %>
          <% end %>
          <br /><br />
        </li>
      </ul>
    </li>
  <% end %>
</ol>

app/views/courses/_form.html.erb
<%= form_for @course do |f| %>
  <div class="error_explanation">
    <% if @course.errors.any? %>
      <h3><%= @course.errors.full_messages.join(", ").downcase.capitalize %>.</h3>
    <% end %>
  </div>
  <div class="frame small">
    <%= f.label :name %><br />
    <%= f.text_field :name, size: "38" %><br />
    <%= f.label :description %><br />
    <%= f.text_area :description, rows: "10" %><br /> 
    <br />
    <%= f.fields_for :booking do |i| %>
      <%= i.label "Classroom" %><br />
      <%= i.collection_select(:classroom_id, Classroom.all, :id, :name) %>
      <br />
      <br />
      <%= i.label :start_date %><br />
      <%= i.date_select :start_date %><br />
      <br />
      <%= i.label :end_date %><br />
      <%= i.date_select :end_date %><br />
      <br />    
    <% end %>
    Daily
    <br />
    <%= f.label :start_time %><br />
    <%= f.number_field :start_time, min: 0, max: 24, step: 1 %> h
    <br />
    <%= f.label :end_time %><br />
    <%= f.number_field :end_time, min: 0, max: 24, step: 1 %> h
    <br />
    <br />
    <%= f.submit "Submit" %>
  </div>
<% end %>
<div class="frame button" >
  <%= button_to "Cancel", courses_path, method: :get %>
</div>

app/views/courses/edit.html.erb
<div class="frame small">
  <h2>Edit</h2>
  <h3><%=@course.name %></h3>
</div>


<%= render 'form' %>

app/views/courses/index.html.erb
<div class="frame small">
  <h2>Courses</h2>
  <%= search_form_for @q do |f| %>
    <%= f.label "Search" %>
    <%= f.text_field :name_cont, placeholder: " enter course name" %>
    <%= f.submit %><br /><br />
  <% end %>
</div>
<div class="frame medium">
  <ul>
    <%= content_tag_for :li, @courses do |course| %>
      <h4>
      <%= link_to course.name, course_path(course) %>
      </h4>
      <br>
      <p>
      <% if course.booking %>
        Start: <%= course.booking.start_date %> | 
        End: <%= course.booking.end_date %> | 
        <%= course.booking.classroom.name %>
      <% end %>
      <br />
      <% if can? :manage, Course %>
        <%= button_to "Edit", edit_course_path(course), method: :get %>
        <%= button_to "Delete", delete_course_path(course) %>
      <% end %>
    </p>
    <% end %>
    <br />
    <% if can? :manage, Course %>
      <li>
        <%= button_to "New Course", new_course_path, method: :get %>
      </li>
    <% end %>
  </ul>
</div>

app/views/courses/new.html.erb
<div class="frame small">
  <h2>New Course</h2>
</div>


<%= render 'form' %>

app/views/courses/show.html.erb
<div class="frame large">
  <h2>
    <%= @course.name %>
  </h2>
  <p>Description: <%= @course.description %></p>
</div>
<div class="frame medium">
  <ul>
    <% if @course.booking %>
      <%= render 'booking' %>
    <% end %>
    <li>
      Start Time: <%= @course.start_time %> h
    </li>
    <li>
      End Time: <%= @course.end_time %> h
    </li>
    <% if can? :manage, Course %>
      <br />
      <li>
        <%= button_to "Edit", edit_course_path(@course), method: :get %>
        <%= button_to "Delete", delete_course_path(@course) %>
      </li>
    <% end %>
    <br />
    <li>
      <%= button_to "Courses", courses_path, method: :get %>
    </li>
  </ul>
</div>
<div class="frame left instructors">
  <h4>Instructors | <%= @course.instructors.count %></h4>
  <% if @course.instructors.any? %>
    <%= render 'assignments' %>
  <% end %>
  <% if can? :manage, Assignment %>
    <%= button_to "Add Instructor", new_course_assignment_path(@course), method: :get %>
  <% end %>
</div>
<% if current_user %>
<div class="frame right students">
    <div class="students">
      <h4>Students | <%= @course.students.count %></h4>
      <% if @course.students.any? %>
        <%= render 'enrollments' %>
      <% end %>
      <% if can? :manage, Enrollment %>
        <%= button_to "Add Student", new_course_enrollment_path(@course), method: :get %>
      <% end %>
    </div>
  </div>
<% end %>