config/routes.rb
GAilyApp::Application.routes.draw do
  
  get "/" => "home#index", as: "home"
  root to: "home#index"

  resources :courses do
    resources :enrollments, only: [:new, :create, :edit, :update, :destroy]
    resources :assignments, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :classrooms
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  post "courses/:id/delete" => "courses#destroy", as: "delete_course"
  post "users/:id/delete" => "users#destroy", as: "delete_user"
  post "classrooms/:id/delete" => "classrooms#destroy", as: "delete_classroom"
  post "courses/:course_id/enrollments/:id" => "enrollments#destroy", as: "delete_course_enrollment"
  post "courses/:course_id/assignments/:id" => "assignments#destroy", as: "delete_course_assignment"

end

app/views/layouts/_flashes.html.erb
<div class="flash">
  <h3>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
    <br />
  </h3>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GAi.ly</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=Francois+One' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div class="logo">
      <%= image_tag("gaily_logo.png") %>
    </div>
    <nav>
      <% if current_user %>
      <li>
        <div class="full_name">
          <%= link_to current_user.full_name, user_path(current_user) %>
        </div>
        <%= link_to "Logout", session_path(0), method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "Login", new_session_path, class: active_menu_item(new_session_path) %>
      </li>
    <% end %>
    <li>
      <%= link_to "Home", home_path, class: active_menu_item(home_path) %>
    </li>
    <li>
      <%= link_to "Courses", courses_path, class: active_menu_item(courses_path) %>
    </li>
    <li>
      <% if current_user %>
        <%= link_to "Users", users_path, class: active_menu_item(users_path) %>
      <% end %>
    </li>
    <% if can? :manage, Classroom %>
      <li>
        <%= link_to "Classrooms", classrooms_path, class: active_menu_item(classrooms_path) %>
      </li>
    <% end %>
    </nav>
  </header>
  <div class="ebthaf">
    <%= render 'layouts/flashes' %>
    
    <%= yield %>
  </div>
  <footer>
  </footer>
</body>
</html>